set -g @plugin 'tmux-plugins/tpm'

# sensible
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'christoomey/vim-tmux-navigator' # tmux和vim无缝切换 需要配合vim插件使用
set -g @plugin 'fabioluciano/tmux-powerkit'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-open' # 打开应用

set -g base-index 1 # 窗口编号从1开始
setw -g pane-base-index 1 # pane编号从1开始
set -g mouse on # 启用鼠标支持
set -g mode-keys vi # 复制模式使用vi键位
# prefix键
unbind C-b
set -g prefix C-g
bind -N "Send the prefix key through to the application" \
  C-g send-prefix
# set -g prefix M-g # prefix键

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
bind-key S setw synchronize-panes # 同步窗格输入
set -s set-clipboard on # 允许与系统剪贴板交互
set -g allow-passthrough on # 允许控制序列

setw -g monitor-activity on # 窗口有活动时提示

set -as terminal-features ',xterm-*:RGB'


# PowerKit Bar
set -g @powerkit_plugins "git,ssh,cpu,memory,battery,datetime" # hostname
set -g @powerkit_theme "catppuccin"
set -g @powerkit_theme_variant "mocha"
# set -g @powerkit_transparent "true"
set -g @powerkit_plugin_datetime_format "%m-%d %H:%M:%S"
set -g @powerkit_status_interval "5"

set -g popup-style 'bg=default'

# Save
set -g @continuum-restore 'on' # 自动恢复功能
set -g @continuum-save-interval '15' # 默认15分钟
set -g @resurrect-capture-pane-contents 'on' # 捕获面板内容以便恢复时显示
# set -g @resurrect-strategy-nvim 'session' # 使用nvim session恢复

bind-key "T" run-shell "sesh connect \"$(
  sesh list --icons | fzf --tmux 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list --icons -t)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list --icons -c)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list --icons -z)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}' \
    -- --ansi
)\""

run '~/.tmux/plugins/tpm/tpm'
